name: amazon_products
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - jupyterlab
  - mlflow=2.1.1
  - numpy
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - matplotlib
  - seaborn
  - pandas
  - git=2.30.2
  - plotly
  - pyppeteer
  - texlive-core
  - nbconvert
  - pip:
      - wandb==0.13.9
      - textblob
      - nltk
      - vaderSentiment
      - scikit-posthocs
